### ISSUE TITLE
Selection is disabled when using this

### ISSUE THREAD

**Issue by aaperesc** [akhilcb/ACBRadialCollectionView#1]
From Apple Documentation:

**collectionView:didSelectItemAtIndexPath:**

The collection view calls this method when the user successfully selects an item in the collection view. **_It does not call this method when you programmatically set the selection._**

Maybe it has something to do with that.

**Comment by akhilcb** [comment]
Please check if you have setup your delegate properly. I just tried it on this project and `didSelectItemAtIndexPath` is getting called when tapped on any cell. Please try to pull latest version and check it out. It should print `indexPath` on console.

**Comment by aaperesc** [comment]
The delegates are setup correctly, they start working as soon as I comment out the lines to initialize this component. Thanks for the reply

**Comment by akhilcb** [comment]
Hi, Could you please try with the sample project and let me know if it is working properly? I am not able to reproduce this issue there.
